### ISSUE TITLE
Can other conditions be used as control signals?

### ISSUE THREAD

**Issue by huo852yan** [Yuanshi9815/OminiControl#11]
Thank you for such excellent work. I am very interested in your work. 
Can other control conditions (semantic segmentation maps, sketches, etc.) be used as control images? 

I am a little confused. Most of the research work claiming to be controllable focuses more on edge/canny maps and depth maps, and few studies focus on semantic segmentation maps and sketches (in the generative models of sdxl and Flux versions). Is it because the result is not good or there is little demand?

**Comment by Yuanshi9815** [comment]
This is a good question. While we haven't trained the model on other control conditions such as segmentation maps and sketches, we believe OmniControl could potentially handle these tasks.

Regarding why most research works (including our OminiControl) focus on canny edge-to-image tasks -- we think it's primarily because canny edges provide a straightforward way to demonstrate a method's capability for condition controlling. Since it's relatively easy to extract canny edges from target images, this makes it convenient for implementation and experimental validation.

**Comment by huo852yan** [comment]
Thanks for your reply. 

I am currently concentrating on achieving precise alignment in image generation using sparse guidance conditions, such as semantic segmentation maps and sketches. 

Your work has provided me with new inspiration. I look forward to exploring more of your research and hope for the opportunity to engage in further discussions with you😊

**Comment by Yuanshi9815** [comment]
Thank you for your interest! Feel free to reach out anytime for discussion.
